name: rick_and_morty_and_flutter
description: A mobile app to fetch data.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  retrofit: ^4.0.1
  built_value: ^8.6.3
  json_annotation: ^4.8.1
  retrofit_generator: ^7.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
     - images/cover.png

  fonts:
  - family:  RaMCustomIcons
    fonts:
     - asset: assets/fonts/RaMCustomIcons.ttf
